[package]
name = "screech"
version = "0.1.0"
authors = ["Samuel Leeuwenburg <samleeuwenburg@gmail.com>"]
edition = "2018"
description = "collection of helpers to handle audio"
repository = "https://github.com/samuelleeuwenburg/screech"
license = "Apache-2.0"
keywords = ["audio"]
